# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Codescrit LLC
email: contact-us@codescrit.com
description: >- # this means to ignore newlines until "baseurl:"
  We are boutique software development company that profives personalized services
  for a select number of customers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codescrit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
markdown: GFM
twitter_username: codescrit
github_username:  codescrit

# Build settings

# theme: jekyll-theme-architect  # Layout 'post', 'page', 'home' requrested in ... does not exist
# theme: jekyll-theme-cayman     # Layout 'post', 'page', 'home' requrested in ... does not exist
# theme: jekyll-theme-dinky      # Layout 'post', 'page', 'home' requrested in ... does not exist
# theme: jekyll-theme-hacker     # page requested
# theme: jekyll-theme-leap-day   # not found
# theme: jekyll-theme-merlot     # not found
# theme: jekyll-theme-midnight   # Layout 'post', 'page', 'home' requrested in ... does not exist
theme: jekyll-theme-hacker
# theme: jekyll-theme-minimal    # not loading
# theme: jekyll-theme-modernist  # not found
# theme: jekyll-theme-primer
# theme: jekyll-theme-slate      # not found
# theme: jekyll-theme-tactile    # not found
# theme: jekyll-theme-time-machine # not found

# remote_theme: benbalter/retlab

plugins:
  - jekyll-feed

github: [metadata]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
